# Defaults for Ping DS install (unzip only; no setup)
ds_install_path: "/opt/apps/opendj"
ds_install_base: "/opt/apps"
ds_zip_name: "DS-8.0.2.zip"
ds_zip_path: "/tmp/{{ ds_zip_name }}"
pingds_install_user: opendj
pingds_install_group: opendj
